<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: http_access_log_service.proto

namespace Logger;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * HTTP访问日志
 *
 * Generated from protobuf message <code>logger.HttpAccessLog</code>
 */
class HttpAccessLog extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string requestId = 48;</code>
     */
    protected $requestId = '';
    /**
     * Generated from protobuf field <code>int64 serverId = 1;</code>
     */
    protected $serverId = 0;
    /**
     * Generated from protobuf field <code>int64 nodeId = 2;</code>
     */
    protected $nodeId = 0;
    /**
     * Generated from protobuf field <code>int64 originId = 5;</code>
     */
    protected $originId = 0;
    /**
     * Generated from protobuf field <code>string remoteAddr = 6;</code>
     */
    protected $remoteAddr = '';
    /**
     * Generated from protobuf field <code>string rawRemoteAddr = 7;</code>
     */
    protected $rawRemoteAddr = '';
    /**
     * Generated from protobuf field <code>int32 remotePort = 8;</code>
     */
    protected $remotePort = 0;
    /**
     * Generated from protobuf field <code>string remoteUser = 9;</code>
     */
    protected $remoteUser = '';
    /**
     * Generated from protobuf field <code>string requestURI = 10;</code>
     */
    protected $requestURI = '';
    /**
     * Generated from protobuf field <code>string requestPath = 11;</code>
     */
    protected $requestPath = '';
    /**
     * Generated from protobuf field <code>int64 requestLength = 12;</code>
     */
    protected $requestLength = 0;
    /**
     * Generated from protobuf field <code>double requestTime = 13;</code>
     */
    protected $requestTime = 0.0;
    /**
     * Generated from protobuf field <code>string requestMethod = 14;</code>
     */
    protected $requestMethod = '';
    /**
     * Generated from protobuf field <code>string requestFilename = 15;</code>
     */
    protected $requestFilename = '';
    /**
     * Generated from protobuf field <code>bytes requestBody = 51;</code>
     */
    protected $requestBody = '';
    /**
     * Generated from protobuf field <code>string scheme = 16;</code>
     */
    protected $scheme = '';
    /**
     * Generated from protobuf field <code>string proto = 17;</code>
     */
    protected $proto = '';
    /**
     * Generated from protobuf field <code>int64 bytesSent = 18;</code>
     */
    protected $bytesSent = 0;
    /**
     * Generated from protobuf field <code>int64 bodyBytesSent = 19;</code>
     */
    protected $bodyBytesSent = 0;
    /**
     * Generated from protobuf field <code>int32 status = 20;</code>
     */
    protected $status = 0;
    /**
     * Generated from protobuf field <code>string statusMessage = 21;</code>
     */
    protected $statusMessage = '';
    /**
     * Generated from protobuf field <code>map<string, .logger.Strings> sentHeader = 22;</code>
     */
    private $sentHeader;
    /**
     * Generated from protobuf field <code>string timeISO8601 = 23;</code>
     */
    protected $timeISO8601 = '';
    /**
     * Generated from protobuf field <code>string timeLocal = 24;</code>
     */
    protected $timeLocal = '';
    /**
     * Generated from protobuf field <code>double msec = 25;</code>
     */
    protected $msec = 0.0;
    /**
     * Generated from protobuf field <code>int64 timestamp = 26;</code>
     */
    protected $timestamp = 0;
    /**
     * Generated from protobuf field <code>string host = 27;</code>
     */
    protected $host = '';
    /**
     * Generated from protobuf field <code>string referer = 28;</code>
     */
    protected $referer = '';
    /**
     * Generated from protobuf field <code>string userAgent = 29;</code>
     */
    protected $userAgent = '';
    /**
     * Generated from protobuf field <code>string request = 30;</code>
     */
    protected $request = '';
    /**
     * Generated from protobuf field <code>string contentType = 31;</code>
     */
    protected $contentType = '';
    /**
     * Generated from protobuf field <code>map<string, string> cookie = 32;</code>
     */
    private $cookie;
    /**
     * Generated from protobuf field <code>string args = 34;</code>
     */
    protected $args = '';
    /**
     * Generated from protobuf field <code>string queryString = 35;</code>
     */
    protected $queryString = '';
    /**
     * Generated from protobuf field <code>map<string, .logger.Strings> header = 36;</code>
     */
    private $header;
    /**
     * Generated from protobuf field <code>string serverName = 37;</code>
     */
    protected $serverName = '';
    /**
     * Generated from protobuf field <code>int32 serverPort = 38;</code>
     */
    protected $serverPort = 0;
    /**
     * Generated from protobuf field <code>string serverProtocol = 39;</code>
     */
    protected $serverProtocol = '';
    /**
     * Generated from protobuf field <code>string hostname = 40;</code>
     */
    protected $hostname = '';
    /**
     * 源站相关
     *
     * Generated from protobuf field <code>string originAddress = 41;</code>
     */
    protected $originAddress = '';
    /**
     * Generated from protobuf field <code>int32 originStatus = 52;</code>
     */
    protected $originStatus = 0;
    /**
     * 错误信息
     *
     * Generated from protobuf field <code>repeated string errors = 42;</code>
     */
    private $errors;
    /**
     * 扩展
     *
     * Generated from protobuf field <code>map<string, string> attrs = 43;</code>
     */
    private $attrs;
    /**
     * WAF相关
     *
     * Generated from protobuf field <code>int64 firewallPolicyId = 44;</code>
     */
    protected $firewallPolicyId = 0;
    /**
     * Generated from protobuf field <code>int64 firewallRuleGroupId = 45;</code>
     */
    protected $firewallRuleGroupId = 0;
    /**
     * Generated from protobuf field <code>int64 firewallRuleSetId = 46;</code>
     */
    protected $firewallRuleSetId = 0;
    /**
     * Generated from protobuf field <code>int64 firewallRuleId = 47;</code>
     */
    protected $firewallRuleId = 0;
    /**
     * Generated from protobuf field <code>repeated string firewallActions = 49;</code>
     */
    private $firewallActions;
    /**
     * Generated from protobuf field <code>repeated string tags = 50;</code>
     */
    private $tags;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $requestId
     *     @type int|string $serverId
     *     @type int|string $nodeId
     *     @type int|string $originId
     *     @type string $remoteAddr
     *     @type string $rawRemoteAddr
     *     @type int $remotePort
     *     @type string $remoteUser
     *     @type string $requestURI
     *     @type string $requestPath
     *     @type int|string $requestLength
     *     @type float $requestTime
     *     @type string $requestMethod
     *     @type string $requestFilename
     *     @type string $requestBody
     *     @type string $scheme
     *     @type string $proto
     *     @type int|string $bytesSent
     *     @type int|string $bodyBytesSent
     *     @type int $status
     *     @type string $statusMessage
     *     @type array|\Google\Protobuf\Internal\MapField $sentHeader
     *     @type string $timeISO8601
     *     @type string $timeLocal
     *     @type float $msec
     *     @type int|string $timestamp
     *     @type string $host
     *     @type string $referer
     *     @type string $userAgent
     *     @type string $request
     *     @type string $contentType
     *     @type array|\Google\Protobuf\Internal\MapField $cookie
     *     @type string $args
     *     @type string $queryString
     *     @type array|\Google\Protobuf\Internal\MapField $header
     *     @type string $serverName
     *     @type int $serverPort
     *     @type string $serverProtocol
     *     @type string $hostname
     *     @type string $originAddress
     *           源站相关
     *     @type int $originStatus
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $errors
     *           错误信息
     *     @type array|\Google\Protobuf\Internal\MapField $attrs
     *           扩展
     *     @type int|string $firewallPolicyId
     *           WAF相关
     *     @type int|string $firewallRuleGroupId
     *     @type int|string $firewallRuleSetId
     *     @type int|string $firewallRuleId
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $firewallActions
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $tags
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\HttpAccessLogService::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string requestId = 48;</code>
     * @return string
     */
    public function getRequestId()
    {
        return $this->requestId;
    }

    /**
     * Generated from protobuf field <code>string requestId = 48;</code>
     * @param string $var
     * @return $this
     */
    public function setRequestId($var)
    {
        GPBUtil::checkString($var, True);
        $this->requestId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 serverId = 1;</code>
     * @return int|string
     */
    public function getServerId()
    {
        return $this->serverId;
    }

    /**
     * Generated from protobuf field <code>int64 serverId = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setServerId($var)
    {
        GPBUtil::checkInt64($var);
        $this->serverId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 nodeId = 2;</code>
     * @return int|string
     */
    public function getNodeId()
    {
        return $this->nodeId;
    }

    /**
     * Generated from protobuf field <code>int64 nodeId = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setNodeId($var)
    {
        GPBUtil::checkInt64($var);
        $this->nodeId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 originId = 5;</code>
     * @return int|string
     */
    public function getOriginId()
    {
        return $this->originId;
    }

    /**
     * Generated from protobuf field <code>int64 originId = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setOriginId($var)
    {
        GPBUtil::checkInt64($var);
        $this->originId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string remoteAddr = 6;</code>
     * @return string
     */
    public function getRemoteAddr()
    {
        return $this->remoteAddr;
    }

    /**
     * Generated from protobuf field <code>string remoteAddr = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setRemoteAddr($var)
    {
        GPBUtil::checkString($var, True);
        $this->remoteAddr = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string rawRemoteAddr = 7;</code>
     * @return string
     */
    public function getRawRemoteAddr()
    {
        return $this->rawRemoteAddr;
    }

    /**
     * Generated from protobuf field <code>string rawRemoteAddr = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setRawRemoteAddr($var)
    {
        GPBUtil::checkString($var, True);
        $this->rawRemoteAddr = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 remotePort = 8;</code>
     * @return int
     */
    public function getRemotePort()
    {
        return $this->remotePort;
    }

    /**
     * Generated from protobuf field <code>int32 remotePort = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setRemotePort($var)
    {
        GPBUtil::checkInt32($var);
        $this->remotePort = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string remoteUser = 9;</code>
     * @return string
     */
    public function getRemoteUser()
    {
        return $this->remoteUser;
    }

    /**
     * Generated from protobuf field <code>string remoteUser = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setRemoteUser($var)
    {
        GPBUtil::checkString($var, True);
        $this->remoteUser = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string requestURI = 10;</code>
     * @return string
     */
    public function getRequestURI()
    {
        return $this->requestURI;
    }

    /**
     * Generated from protobuf field <code>string requestURI = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setRequestURI($var)
    {
        GPBUtil::checkString($var, True);
        $this->requestURI = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string requestPath = 11;</code>
     * @return string
     */
    public function getRequestPath()
    {
        return $this->requestPath;
    }

    /**
     * Generated from protobuf field <code>string requestPath = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setRequestPath($var)
    {
        GPBUtil::checkString($var, True);
        $this->requestPath = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 requestLength = 12;</code>
     * @return int|string
     */
    public function getRequestLength()
    {
        return $this->requestLength;
    }

    /**
     * Generated from protobuf field <code>int64 requestLength = 12;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRequestLength($var)
    {
        GPBUtil::checkInt64($var);
        $this->requestLength = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double requestTime = 13;</code>
     * @return float
     */
    public function getRequestTime()
    {
        return $this->requestTime;
    }

    /**
     * Generated from protobuf field <code>double requestTime = 13;</code>
     * @param float $var
     * @return $this
     */
    public function setRequestTime($var)
    {
        GPBUtil::checkDouble($var);
        $this->requestTime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string requestMethod = 14;</code>
     * @return string
     */
    public function getRequestMethod()
    {
        return $this->requestMethod;
    }

    /**
     * Generated from protobuf field <code>string requestMethod = 14;</code>
     * @param string $var
     * @return $this
     */
    public function setRequestMethod($var)
    {
        GPBUtil::checkString($var, True);
        $this->requestMethod = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string requestFilename = 15;</code>
     * @return string
     */
    public function getRequestFilename()
    {
        return $this->requestFilename;
    }

    /**
     * Generated from protobuf field <code>string requestFilename = 15;</code>
     * @param string $var
     * @return $this
     */
    public function setRequestFilename($var)
    {
        GPBUtil::checkString($var, True);
        $this->requestFilename = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes requestBody = 51;</code>
     * @return string
     */
    public function getRequestBody()
    {
        return $this->requestBody;
    }

    /**
     * Generated from protobuf field <code>bytes requestBody = 51;</code>
     * @param string $var
     * @return $this
     */
    public function setRequestBody($var)
    {
        GPBUtil::checkString($var, False);
        $this->requestBody = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string scheme = 16;</code>
     * @return string
     */
    public function getScheme()
    {
        return $this->scheme;
    }

    /**
     * Generated from protobuf field <code>string scheme = 16;</code>
     * @param string $var
     * @return $this
     */
    public function setScheme($var)
    {
        GPBUtil::checkString($var, True);
        $this->scheme = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string proto = 17;</code>
     * @return string
     */
    public function getProto()
    {
        return $this->proto;
    }

    /**
     * Generated from protobuf field <code>string proto = 17;</code>
     * @param string $var
     * @return $this
     */
    public function setProto($var)
    {
        GPBUtil::checkString($var, True);
        $this->proto = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 bytesSent = 18;</code>
     * @return int|string
     */
    public function getBytesSent()
    {
        return $this->bytesSent;
    }

    /**
     * Generated from protobuf field <code>int64 bytesSent = 18;</code>
     * @param int|string $var
     * @return $this
     */
    public function setBytesSent($var)
    {
        GPBUtil::checkInt64($var);
        $this->bytesSent = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 bodyBytesSent = 19;</code>
     * @return int|string
     */
    public function getBodyBytesSent()
    {
        return $this->bodyBytesSent;
    }

    /**
     * Generated from protobuf field <code>int64 bodyBytesSent = 19;</code>
     * @param int|string $var
     * @return $this
     */
    public function setBodyBytesSent($var)
    {
        GPBUtil::checkInt64($var);
        $this->bodyBytesSent = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 status = 20;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>int32 status = 20;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkInt32($var);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string statusMessage = 21;</code>
     * @return string
     */
    public function getStatusMessage()
    {
        return $this->statusMessage;
    }

    /**
     * Generated from protobuf field <code>string statusMessage = 21;</code>
     * @param string $var
     * @return $this
     */
    public function setStatusMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->statusMessage = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, .logger.Strings> sentHeader = 22;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getSentHeader()
    {
        return $this->sentHeader;
    }

    /**
     * Generated from protobuf field <code>map<string, .logger.Strings> sentHeader = 22;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setSentHeader($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Logger\Strings::class);
        $this->sentHeader = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string timeISO8601 = 23;</code>
     * @return string
     */
    public function getTimeISO8601()
    {
        return $this->timeISO8601;
    }

    /**
     * Generated from protobuf field <code>string timeISO8601 = 23;</code>
     * @param string $var
     * @return $this
     */
    public function setTimeISO8601($var)
    {
        GPBUtil::checkString($var, True);
        $this->timeISO8601 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string timeLocal = 24;</code>
     * @return string
     */
    public function getTimeLocal()
    {
        return $this->timeLocal;
    }

    /**
     * Generated from protobuf field <code>string timeLocal = 24;</code>
     * @param string $var
     * @return $this
     */
    public function setTimeLocal($var)
    {
        GPBUtil::checkString($var, True);
        $this->timeLocal = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double msec = 25;</code>
     * @return float
     */
    public function getMsec()
    {
        return $this->msec;
    }

    /**
     * Generated from protobuf field <code>double msec = 25;</code>
     * @param float $var
     * @return $this
     */
    public function setMsec($var)
    {
        GPBUtil::checkDouble($var);
        $this->msec = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 timestamp = 26;</code>
     * @return int|string
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    /**
     * Generated from protobuf field <code>int64 timestamp = 26;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTimestamp($var)
    {
        GPBUtil::checkInt64($var);
        $this->timestamp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string host = 27;</code>
     * @return string
     */
    public function getHost()
    {
        return $this->host;
    }

    /**
     * Generated from protobuf field <code>string host = 27;</code>
     * @param string $var
     * @return $this
     */
    public function setHost($var)
    {
        GPBUtil::checkString($var, True);
        $this->host = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string referer = 28;</code>
     * @return string
     */
    public function getReferer()
    {
        return $this->referer;
    }

    /**
     * Generated from protobuf field <code>string referer = 28;</code>
     * @param string $var
     * @return $this
     */
    public function setReferer($var)
    {
        GPBUtil::checkString($var, True);
        $this->referer = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string userAgent = 29;</code>
     * @return string
     */
    public function getUserAgent()
    {
        return $this->userAgent;
    }

    /**
     * Generated from protobuf field <code>string userAgent = 29;</code>
     * @param string $var
     * @return $this
     */
    public function setUserAgent($var)
    {
        GPBUtil::checkString($var, True);
        $this->userAgent = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string request = 30;</code>
     * @return string
     */
    public function getRequest()
    {
        return $this->request;
    }

    /**
     * Generated from protobuf field <code>string request = 30;</code>
     * @param string $var
     * @return $this
     */
    public function setRequest($var)
    {
        GPBUtil::checkString($var, True);
        $this->request = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string contentType = 31;</code>
     * @return string
     */
    public function getContentType()
    {
        return $this->contentType;
    }

    /**
     * Generated from protobuf field <code>string contentType = 31;</code>
     * @param string $var
     * @return $this
     */
    public function setContentType($var)
    {
        GPBUtil::checkString($var, True);
        $this->contentType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, string> cookie = 32;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getCookie()
    {
        return $this->cookie;
    }

    /**
     * Generated from protobuf field <code>map<string, string> cookie = 32;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setCookie($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->cookie = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string args = 34;</code>
     * @return string
     */
    public function getArgs()
    {
        return $this->args;
    }

    /**
     * Generated from protobuf field <code>string args = 34;</code>
     * @param string $var
     * @return $this
     */
    public function setArgs($var)
    {
        GPBUtil::checkString($var, True);
        $this->args = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string queryString = 35;</code>
     * @return string
     */
    public function getQueryString()
    {
        return $this->queryString;
    }

    /**
     * Generated from protobuf field <code>string queryString = 35;</code>
     * @param string $var
     * @return $this
     */
    public function setQueryString($var)
    {
        GPBUtil::checkString($var, True);
        $this->queryString = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, .logger.Strings> header = 36;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getHeader()
    {
        return $this->header;
    }

    /**
     * Generated from protobuf field <code>map<string, .logger.Strings> header = 36;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setHeader($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Logger\Strings::class);
        $this->header = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string serverName = 37;</code>
     * @return string
     */
    public function getServerName()
    {
        return $this->serverName;
    }

    /**
     * Generated from protobuf field <code>string serverName = 37;</code>
     * @param string $var
     * @return $this
     */
    public function setServerName($var)
    {
        GPBUtil::checkString($var, True);
        $this->serverName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 serverPort = 38;</code>
     * @return int
     */
    public function getServerPort()
    {
        return $this->serverPort;
    }

    /**
     * Generated from protobuf field <code>int32 serverPort = 38;</code>
     * @param int $var
     * @return $this
     */
    public function setServerPort($var)
    {
        GPBUtil::checkInt32($var);
        $this->serverPort = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string serverProtocol = 39;</code>
     * @return string
     */
    public function getServerProtocol()
    {
        return $this->serverProtocol;
    }

    /**
     * Generated from protobuf field <code>string serverProtocol = 39;</code>
     * @param string $var
     * @return $this
     */
    public function setServerProtocol($var)
    {
        GPBUtil::checkString($var, True);
        $this->serverProtocol = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string hostname = 40;</code>
     * @return string
     */
    public function getHostname()
    {
        return $this->hostname;
    }

    /**
     * Generated from protobuf field <code>string hostname = 40;</code>
     * @param string $var
     * @return $this
     */
    public function setHostname($var)
    {
        GPBUtil::checkString($var, True);
        $this->hostname = $var;

        return $this;
    }

    /**
     * 源站相关
     *
     * Generated from protobuf field <code>string originAddress = 41;</code>
     * @return string
     */
    public function getOriginAddress()
    {
        return $this->originAddress;
    }

    /**
     * 源站相关
     *
     * Generated from protobuf field <code>string originAddress = 41;</code>
     * @param string $var
     * @return $this
     */
    public function setOriginAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->originAddress = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 originStatus = 52;</code>
     * @return int
     */
    public function getOriginStatus()
    {
        return $this->originStatus;
    }

    /**
     * Generated from protobuf field <code>int32 originStatus = 52;</code>
     * @param int $var
     * @return $this
     */
    public function setOriginStatus($var)
    {
        GPBUtil::checkInt32($var);
        $this->originStatus = $var;

        return $this;
    }

    /**
     * 错误信息
     *
     * Generated from protobuf field <code>repeated string errors = 42;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getErrors()
    {
        return $this->errors;
    }

    /**
     * 错误信息
     *
     * Generated from protobuf field <code>repeated string errors = 42;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setErrors($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->errors = $arr;

        return $this;
    }

    /**
     * 扩展
     *
     * Generated from protobuf field <code>map<string, string> attrs = 43;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getAttrs()
    {
        return $this->attrs;
    }

    /**
     * 扩展
     *
     * Generated from protobuf field <code>map<string, string> attrs = 43;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setAttrs($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->attrs = $arr;

        return $this;
    }

    /**
     * WAF相关
     *
     * Generated from protobuf field <code>int64 firewallPolicyId = 44;</code>
     * @return int|string
     */
    public function getFirewallPolicyId()
    {
        return $this->firewallPolicyId;
    }

    /**
     * WAF相关
     *
     * Generated from protobuf field <code>int64 firewallPolicyId = 44;</code>
     * @param int|string $var
     * @return $this
     */
    public function setFirewallPolicyId($var)
    {
        GPBUtil::checkInt64($var);
        $this->firewallPolicyId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 firewallRuleGroupId = 45;</code>
     * @return int|string
     */
    public function getFirewallRuleGroupId()
    {
        return $this->firewallRuleGroupId;
    }

    /**
     * Generated from protobuf field <code>int64 firewallRuleGroupId = 45;</code>
     * @param int|string $var
     * @return $this
     */
    public function setFirewallRuleGroupId($var)
    {
        GPBUtil::checkInt64($var);
        $this->firewallRuleGroupId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 firewallRuleSetId = 46;</code>
     * @return int|string
     */
    public function getFirewallRuleSetId()
    {
        return $this->firewallRuleSetId;
    }

    /**
     * Generated from protobuf field <code>int64 firewallRuleSetId = 46;</code>
     * @param int|string $var
     * @return $this
     */
    public function setFirewallRuleSetId($var)
    {
        GPBUtil::checkInt64($var);
        $this->firewallRuleSetId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 firewallRuleId = 47;</code>
     * @return int|string
     */
    public function getFirewallRuleId()
    {
        return $this->firewallRuleId;
    }

    /**
     * Generated from protobuf field <code>int64 firewallRuleId = 47;</code>
     * @param int|string $var
     * @return $this
     */
    public function setFirewallRuleId($var)
    {
        GPBUtil::checkInt64($var);
        $this->firewallRuleId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string firewallActions = 49;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFirewallActions()
    {
        return $this->firewallActions;
    }

    /**
     * Generated from protobuf field <code>repeated string firewallActions = 49;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFirewallActions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->firewallActions = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string tags = 50;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTags()
    {
        return $this->tags;
    }

    /**
     * Generated from protobuf field <code>repeated string tags = 50;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTags($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->tags = $arr;

        return $this;
    }

}

